name: ServerTools
version: '${project.version}'
main: net.duckycraft.server_tools.ServerTools
api-version: '1.21'
commands:
    vanish:
        description: Vanish command
        usage: /<command>
        aliases: [v, vanishplayer, vp]
        permission: servertools.vanish
    msg:
        description: A Mojang provided command
        usage: /<command>
    w:
        description: A Mojang provided command
        usage: /<command>
    tell:
        description: A Mojang provided command
        usage: /<command>